# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("notas", models.TextField(blank=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="ItemInventario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("dimensiones", models.CharField(blank=True, max_length=100)),
                ("capacidad_personas", models.PositiveIntegerField(blank=True, null=True)),
                ("precio_base", models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="inventario/")),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "item de inventario",
                "verbose_name_plural": "inventario",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenReferencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("imagen", models.ImageField(upload_to="referencias/")),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imagenes_referencia",
                        to="FiestaEntreOso_app.iteminventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de referencia",
                "verbose_name_plural": "imágenes de referencia",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
